### ISSUE TITLE
Cannot set property 'next' of undefined

### ISSUE THREAD

**Issue by avoidwork** [avoidwork/tiny-lru#7]
```console
D:\Projects\jasonmulligan.com\node_modules\tiny-lru\lib\tiny-lru.es6.js:159
				first.next = key;
				           ^

TypeError: Cannot set property 'next' of undefined
    at LRU.set (D:\Projects\jasonmulligan.com\node_modules\tiny-lru\lib\tiny-lru.es6.js:159:16)
    at ETag.register (D:\Projects\jasonmulligan.com\node_modules\tiny-etag\lib\etag.js:101:14)
    at ServerResponse.res.on (D:\Projects\jasonmulligan.com\node_modules\tiny-etag\lib\etag.js:65:11)
    at emitNone (events.js:91:20)
    at ServerResponse.emit (events.js:188:7)
    at onFinish (_http_outgoing.js:592:10)
    at afterWrite (_stream_writable.js:383:3)
    at _combinedTickCallback (internal/process/next_tick.js:86:20)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by avoidwork** [comment]
I don't think the `set()` function should be doing a validation check on a property; probably a bug in `remove()`
